name: Install PostgreSQL (failed)

on: 
  push:
    branches:
      - 'failed'

jobs:

  ubuntu-marketplace:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '11'
        postgresql db: 'postgres'
        postgresql user: 'postgres'
    - name: Check Postgres running
      run: |
        sleep 1m
        psql -U postgres -d postgres -h localhost -c "SELECT version()"