name: Install PostgreSQL

on: 
  push:
    branches:
      - 'master'

jobs:

  ubuntu-marketplace:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '12'
        postgresql db: 'postgres'
        postgresql user: 'postgres'
        postgresql password: 'postgres'
    - name: Collect Docker Logs
      uses: jwalton/gh-docker-logs@v1.0.0
    - name: Check running containers
      run: docker ps -a        
    - name: Check Postgres running
      run: |
        sleep 10s
        PGPASSWORD=postgres psql -U postgres -d postgres -h localhost -c "SELECT version()"

  ubuntu-service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check Postgres running
      run: |
        PGPASSWORD=postgres psql -U postgres -d postgres -h localhost -c "SELECT version()"

  ubuntu-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PostgreSQL
      run: |
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt update
        sudo apt install postgresql-12
    - name: Check Postgres running
      run: |
        sudo -u postgres psql -c "SELECT version()"

  windows-binaries:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PostgreSQL
      run: |
        curl https://get.enterprisedb.com/postgresql/postgresql-12.2-1-windows-x64-binaries.zip --output pgsql12.zip
        Expand-Archive 'pgsql12.zip' -Force
        $env:path += ";$(Get-Location)\pgsql12\pgsql\bin\"
        $env:path -split ";"
        initdb -D pgsql12\data -U postgres
        pg_ctl -D pgsql12\data start      
    - name: Check Postgres running
      run: |
        pgsql12\pgsql\bin\psql -U postgres -d postgres -c "SELECT version()"

  macos-binaries:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PostgreSQL
      shell: pwsh
      run: |
        curl https://get.enterprisedb.com/postgresql/postgresql-12.2-1-osx-binaries.zip --output pgsql12.zip
        Expand-Archive 'pgsql12.zip' -Force
        pgsql12/pgsql/bin/initdb -D pgsql12/data -U postgres
        pgsql12/pgsql/bin/pg_ctl -D pgsql12/data start      
    - name: Check Postgres running
      shell: pwsh
      run: |
        pgsql12/pgsql/bin/psql -U postgres -d postgres -c "SELECT version()"